import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Academic class/section (Phase 1).
 *
 * - One class is inside one grade level and one academic year.
 * - The "section letter" (A, B, C, ...) is generated by the backend using:
 *   letters[grade_classes_count]
 *   where grade_classes_count is the number of existing non-deleted classes
 *   for the same (school_id, grade_level_id, academic_year_id).
 */
export class CreateClassesTable1742720000000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS classes (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        school_id uuid NOT NULL REFERENCES schools(id) ON DELETE CASCADE,

        grade_level_id uuid NOT NULL REFERENCES grade_levels(id) ON DELETE CASCADE,
        academic_year_id uuid NOT NULL REFERENCES academic_years(id) ON DELETE CASCADE,

        section_letter varchar(5) NOT NULL,
        name jsonb NOT NULL,
        capacity integer NOT NULL,

        homeroom_teacher_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,

        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now(),
        deleted_at timestamptz
      )
    `);

    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS IDX_classes_school_id
      ON classes (school_id)
    `);

    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS IDX_classes_grade_level_year
      ON classes (grade_level_id, academic_year_id)
    `);

    // Soft-delete aware uniqueness: only one non-deleted class per (grade, year, letter).
    await queryRunner.query(`
      CREATE UNIQUE INDEX IF NOT EXISTS UQ_classes_grade_year_letter
      ON classes (school_id, grade_level_id, academic_year_id, section_letter)
      WHERE deleted_at IS NULL
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP INDEX IF EXISTS UQ_classes_grade_year_letter`);
    await queryRunner.query(`DROP INDEX IF EXISTS IDX_classes_grade_level_year`);
    await queryRunner.query(`DROP INDEX IF EXISTS IDX_classes_school_id`);
    await queryRunner.query(`DROP TABLE IF EXISTS classes`);
  }
}

